version: "2"
services:
  mongodb:
    image: "mongo"
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME='root'
      - ME_CONFIG_MONGODB_ADMINPASSWORD='%%&change-this-please'
    volumes:
      - "kitcoin_db_volume:/data/db"
  kitcoin-main:
    restart: always
    build: .
    image: docker.pkg.github.com/chromezoneeths/kitcoin/kitcoin:debug
    command: node --inspect=0.0.0.0:9229 bin/www
    ports:
      - "9876:9876"
      - "9229:9229"
    links:
      - "mongodb"
    depends_on:
      - mongodb
    env_file: oauth.env
    environment:
      - DATABASE_ADDRESS=mongodb://mongodb
      - DATABASE_NAME=kitcoin
      - DATABASE_USER=root # Unused
      - DATABASE_PORT=33060 # Unused
      - DATABASE_PASSWORD=%%&change-this-please # Unused
      - WAIT_TO_CONNECT=0 # Number of seconds to wait before connecting to db
      - OAUTH_CALLBACK_URL=http://127.0.0.1:9876/oauth
      - ENABLE_REMOTE=1 # Should be 0 in production unless needed, enables admin endpoints.
volumes:
  kitcoin_db_volume:
