version: "2"
services:
  mongodb:
    image: "mongo"
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME='root'
      - ME_CONFIG_MONGODB_ADMINPASSWORD='%%&change-this-please'
    volumes:
      - "kitcoin_db_volume:/data/db"
  kitcoin-main:
    restart: always
    build: . # Replace this with a container tag in production
    ports:
      - "9876:9876"
    links:
      - "mongodb"
    depends_on:
      - mongodb
    environment:
      - DATABASE_ADDRESS=mongodb://mongodb
      - DATABASE_NAME=kitcoin
      - DATABASE_USER=root # Unused
      - DATABASE_PORT=33060 # Unused
      - DATABASE_PASSWORD=%%&change-this-please # Unused
      - WAIT_TO_CONNECT=0 # Number of seconds to wait before connecting to db
      - OAUTH_CALLBACK_URL=http://127.0.0.1:9876/oauth
      - OAUTH_CLIENT_ID="Your client ID goes here"
      - OAUTH_CLIENT_SECRET="Your client secret goes here"
      - ENABLE_REMOTE=1 # Should be 0 in production unless needed, enables admin endpoints.
volumes:
  kitcoin_db_volume:
