version: "3"

services:
 kc:
  build: .
  ports:
   - '5000:5000'
  environment: 
   MONGO_ADDR: db
   MONGO_USER: kcuser
   MONGO_PASS: kcpass
   MONGO_DBNAME: kitcoin
  depends_on: 
   - db
 db:
  image: mongo
  environment: 
   MONGO_INITDB_DATABASE: kitcoin
   MONGO_INITDB_ROOT_USERNAME: kcuser
   MONGO_INITDB_ROOT_PASSWORD: kcpass
  volumes:
   - './data:/data/db'