FROM node:14
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run-script ci

FROM node:14
WORKDIR /app
EXPOSE 9876
CMD npm test
COPY --from=0 --chown=0:0 /app/dist ./dist
COPY --from=0 /app/clientJs ./clientJs
COPY --from=0 /app/bin ./bin
COPY --from=0 /app/test ./test
COPY --from=0 /app/package*.json ./
COPY --from=0 /app/node_modules ./node_modules
